dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install .
  - pip install pytest

script:
  - pytest -k 'not test_list_folder and not test_upload_file_with_folder and not test_running_conversions_with_folder'
